name: Build

'env':
  'GO_VERSION': '1.20.12'

'on':
  'push':
    'tags':
      - 'v*'
    'branches':
      - '*'
  'pull_request':
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '${{ env.GO_VERSION }}'
      - name: Build release
        run: |-
          set -e -u -x

          RELEASE_VERSION="${GITHUB_REF##*/}"
          if [[ "${RELEASE_VERSION}" != v* ]]; then RELEASE_VERSION='dev'; fi
          echo "RELEASE_VERSION=\"${RELEASE_VERSION}\"" >> $GITHUB_ENV

          make VERBOSE=1 VERSION="${RELEASE_VERSION}" release

          ls -l build/dnsproxy-*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: |
            build/dnsproxy-*.tar.gz
            build/dnsproxy-*.zip
